"""Add transit fields to TripItem

Revision ID: 79f4113187fb
Revises: 49c47b1b8d0f
Create Date: 2026-04-30 15:02:52.014716

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '79f4113187fb'
down_revision = '49c47b1b8d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tripitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='place'))
        batch_op.add_column(sa.Column('transit_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('arrival_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('arrival_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tripitem', schema=None) as batch_op:
        batch_op.drop_column('arrival_location')
        batch_op.drop_column('arrival_time')
        batch_op.drop_column('transit_mode')
        batch_op.drop_column('type')

    # ### end Alembic commands ###

